### ISSUE TITLE
Documentation Request: Reference to Refresh Token usage in README?

### ISSUE THREAD

**Issue by gtk-aschmidt** [docusign/code-examples-php#7]
I see that the examples retrieve, but do not make use of the Refresh Token.

I understand that their use may be out of scope for this example.

However, it might be helpful to put a pointer to their SDK usage in the README. There are references to other information sources that are also out of scope, so I feel like it isn't unreasonable to request such a reference here.

If their absence from the documentation is because they are absent from the SDK, a note to the effect that they are non-functional would be helpful. At least I could stop looking for a feature that isn't yet production-ready.

**Comment by LarryKlugerDS** [comment]
Hi @gtk-aschmidt ,
Thank you for raising this issue. As you've noticed, our SDK documentation has a (very) long ways to go. We're aware of that and we will be working on it this year.

For OAuth, our oauth flows closely match oauth2 standards, so we feel that developers do not need to rely on us as a first source of information--especially for the Authorization Code grant flow, where we highly recommend the use of OAuth libraries (not produced by DocuSign) by developers.

For example, I used the  PHP OAuth 2.0 Client package in this example. It includes support for [refreshing a token](https://oauth2-client.thephpleague.com/usage/#refreshing-a-token).

We prefer that developers use a library (including the refresh) operation vs including the software and documentation in the SDK itself. 

We have documented how to use the [refresh operation](https://developers.docusign.com/esign-rest-api/guides/authentication/oauth2-code-grant#using-refresh-tokens) within our API reference for the OAuth flow.

**For the JWT flow,** we do support it from the SDK since developers have less familiarity with it. And it does need to be properly documented for each SDK, that's part of the documentation plan.

If there is software in the SDK that doesn't work, please file an issue so I can raise an internal bug report to our engineering group.
